### ISSUE TITLE
User building workflow?

### ISSUE THREAD

**Issue by Famicoman** [SeattleMeshnet/meshbox#47]
Suppose I get a new router that needs me to target ar71xx, and I'm running untouched/stock firmware. What steps to I take to build a binary and deploy it? I see a few she'll scripts but little in the way of directions other than how to develop. I also see some Readme files of noting of existing binaries but they all appear to be x86 judging by the naming conventions.

Thanks,
Mike.

**Comment by lgierth** [comment]
The cjdns and luci-app-cjdns packages are part of the official openwrt-routing feed since 15.05, so you can just grab the 15.05 firmware image for your respective device, and install them using the Luci UI, or via shell: `opkg update && opkg install luci-app-cjdns`.

The openwrt-routing feed is here: https://github.com/openwrt-routing/packages
